# Generated by Django 3.2.7 on 2023-08-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('new', models.CharField(max_length=100)),
                ('new1', models.CharField(max_length=100)),
            ],
        ),
    ]
