# Generated by Django 3.2.7 on 2023-08-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeting',
            name='new',
        ),
        migrations.RemoveField(
            model_name='greeting',
            name='new1',
        ),
    ]
