# Generated by Django 3.2.7 on 2023-08-11 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0002_auto_20230809_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='NEw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
