# Generated by Django 3.2.7 on 2023-08-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weborm', '0003_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NEw',
        ),
    ]
